version: '3'
services:
  app:
    build:
      context: app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./app:/app
    ports:
      - '5000:5000'
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:latest
  command: sh -c "redis-server --requirepass $REDIS_PASSWORD"
